# Generated by Django 4.1.3 on 2023-01-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joinDate',
            new_name='join_date',
        ),
    ]
