# Generated by Django 4.1.3 on 2023-01-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0002_remove_order_isabandoned_remove_order_iscompleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_items',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateCompleted',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
