# Generated by Django 4.1.3 on 2023-01-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts_api', '0004_alter_cartitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='carts_api.cartitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paypal'), (2, 'Przelewy24')], default=1),
        ),
    ]
