# Generated by Django 4.1.3 on 2023-01-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0005_order_customer_order_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
