# Generated by Django 4.1.3 on 2023-01-16 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_remove_coupon_expirationdate_coupon_days_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts_api', '0006_order_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_items', models.ManyToManyField(to='shop_api.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
