# Generated by Django 4.1.3 on 2023-01-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='dateAdded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discountPercent',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dateAdded',
            new_name='date_added',
        ),
    ]
