# Generated by Django 4.1.3 on 2022-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_category_coupon_product_address_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
