# Generated by Django 4.1.3 on 2022-12-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discout',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
    ]
